name: setup-sundials
description: build and cache sundials module
inputs:
  sundials_ver:
    description: sundials version
    required: true
runs:
  using: composite
  steps:
    - id: cache-sundials
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.MODULES_DIR }}/opt/sundials/${{ inputs.sundials_ver }}
          ${{ env.MODULES_DIR }}/modulefiles/sundials/${{ inputs.sundials_ver }}
        key: ${{ env.OS_VERSION }}-sundials-${{ inputs.sundials_ver }}-${{ hashFiles('scripts/install_sundials.sh') }}
        restore-keys: |
          ${{ env.OS_VERSION }}-sundials-${{ inputs.sundials_ver }}-
    
    - name: build and install sundials module
      if: steps.cache-sundials.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: ./scripts/install_sundials.sh --version=${{ inputs.sundials_ver }} --modules-dir=${{ env.MODULES_DIR }}
      shell: bash
        
    - name: test sundials module
      run: |
        module load sundials/${{ inputs.sundials_ver }}
        module test sundials/${{ inputs.sundials_ver }}
      shell: bash --login -e -o pipefail {0}  # login to load /etc/profile.d/modules.sh
