name: setup-sundials
description: build and cache sundials module
inputs:
  sundials_ver:
    description: sundials version
    required: true
runs:
  using: composite
  steps:
    - id: set-env
      uses: ./.github/actions/set-env

    - id: cache-sundials
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.set-env.outputs.modules_dir }}/opt/sundials/${{ inputs.sundials_ver }}
          ${{ steps.set-env.outputs.modules_dir }}/modulefiles/sundials/${{ inputs.sundials_ver }}
        key: |
          ${{ steps.set-env.outputs.os_ver }}-sundials-${{ inputs.sundials_ver }}-${{ hashFiles('scripts/install_sundials.sh') }}
        restore-keys: |
          ${{ steps.set-env.outputs.os_ver }}-sundials-${{ inputs.sundials_ver }}-

    - name: build and install sundials module
      if: steps.cache-sundials.outputs.cache-hit != 'true'
      run: |
        ./install_sundials.sh \
          --version=${{ inputs.sundials_ver }} \
          --modules-dir=${{ steps.set-env.outputs.modules_dir }}
      working-directory: ${{ github.workspace }}/scripts
      shell: bash

    - name: test sundials module
      run: |
        module use ${{ steps.set-env.outputs.modules_dir }}/modulefiles
        module load sundials/${{ inputs.sundials_ver }}
        module test sundials/${{ inputs.sundials_ver }}
      shell: bash --login -e -o pipefail {0} # login to source /etc/profile.d/modules.sh
