name: setup-defaults
description: setup environment and dependencies
runs:
  using: composite
  steps:
    - id: set-env
      uses: ./.github/actions/set-env

    - name: install os dependencies
      run: ./scripts/setup_${{ steps.set-env.outputs.os_ver }}.sh
      shell: bash

    - name: test module command
      run: |
        source /etc/profile.d/modules.sh
        module avail
      shell: bash
