name: setup-petsc_hdf5
description: Build and cache petsc_hdf5 module
inputs:
  os:
    description: OS
    required: true
  modules_dir:
    description: Modules base directory
    required: true
  petsc_ver:
    description: PETSc version
    required: true
  hdf5_ver:
    description: HDF5 version
    required: true
  petsc_arch:
    description: PETSC_ARCH
    required: true
runs:
  using: composite
  steps:
    - name: Cache petsc_hdf5 module
      id: cache-petsc_hdf5
      uses: actions/cache@v3
      with:
        path: |
          ${{ inputs.modules_dir }}/opt/petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}
          ${{ inputs.modules_dir }}/modulefiles/petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}/${{ inputs.petsc_arch }}
        key: ${{ inputs.os }}-petsc_hdf5-${{ inputs.petsc_ver }}-${{ inputs.hdf5_ver }}-${{ inputs.petsc_arch }}-${{ hashFiles('scripts/install_petsc_hdf5.sh') }}
    
    - name: Build and install petsc_hdf5 module
      if: steps.cache-petsc_hdf5.outputs.cache-hit != 'true'
      run: ./scripts/install_petsc_hdf5.sh --petsc-version=${{ inputs.petsc_ver }} --hdf5-version=${{ inputs.hdf5_ver }} --petsc-arch=${{ inputs.petsc_arch }} --modules-dir=${{ inputs.modules_dir }}
      shell: bash

    - name: Check petsc_hdf5 module
      run: |
        module load petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}/${{ inputs.petsc_arch }}
        module test petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}/${{ inputs.petsc_arch }}
      shell: bash --login -e -o pipefail {0}  # login to load `module` from /etc/profile.d
