name: setup-petsc_hdf5
description: build and cache petsc_hdf5 module
inputs:
  petsc_ver:
    description: petsc version
    required: true
  hdf5_ver:
    description: hdf5 version
    required: true
  petsc_arch:
    description: petsc arch
    required: true
runs:
  using: composite
  steps:
    - id: set-env
      uses: ./.github/actions/set-env

    - id: cache-petsc_hdf5
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.set-env.outputs.modules_dir }}/opt/petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}
          ${{ steps.set-env.outputs.modules_dir }}/modulefiles/petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}/${{ inputs.petsc_arch }}
        key: |
          ${{ steps.set-env.outputs.os_ver }}-petsc_hdf5-${{ inputs.petsc_ver }}-${{ inputs.hdf5_ver }}-${{ inputs.petsc_arch }}-${{ hashFiles('scripts/install_petsc_hdf5.sh') }}
        restore-keys: |
          ${{ steps.set-env.outputs.os_ver }}-petsc_hdf5-${{ inputs.petsc_ver }}-${{ inputs.hdf5_ver }}-${{ inputs.petsc_arch }}-

    - name: build and install petsc_hdf5 module
      if: steps.cache-petsc_hdf5.outputs.cache-hit != 'true'
      run: |
        ./install_petsc_hdf5.sh \
          --petsc-version=${{ inputs.petsc_ver }} \
          --hdf5-version=${{ inputs.hdf5_ver }} \
          --petsc-arch=${{ inputs.petsc_arch }} \
          --modules-dir=${{ steps.set-env.outputs.modules_dir }}
      working-directory: ${{ github.workspace }}/scripts
      shell: bash

    - name: test petsc_hdf5 module
      run: |
        module use ${{ steps.set-env.outputs.modules_dir }}/modulefiles
        module load petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}/${{ inputs.petsc_arch }}
        module test petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}/${{ inputs.petsc_arch }}
      shell: bash --login -e -o pipefail {0} # login to source /etc/profile.d/modules.sh
