name: setup-petsc_hdf5
description: build and cache petsc_hdf5 module
inputs:
  petsc_ver:
    description: petsc version
    required: true
  hdf5_ver:
    description: hdf5 version
    required: true
  petsc_arch:
    description: petsc arch
    required: true
runs:
  using: composite
  steps:
    - id: cache-petsc_hdf5
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.MODULES_DIR }}/opt/petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}
          ${{ env.MODULES_DIR }}/modulefiles/petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}/${{ inputs.petsc_arch }}
        key: ${{ env.OS_VERSION }}-petsc_hdf5-${{ inputs.petsc_ver }}-${{ inputs.hdf5_ver }}-${{ inputs.petsc_arch }}-${{ hashFiles('scripts/install_petsc_hdf5.sh') }}
        restore-keys: |
          ${{ env.OS_VERSION }}-petsc_hdf5-${{ inputs.petsc_ver }}-${{ inputs.hdf5_ver }}-${{ inputs.petsc_arch }}-
    
    - name: build and install petsc_hdf5 module
      if: steps.cache-petsc_hdf5.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: ./scripts/install_petsc_hdf5.sh --petsc-version=${{ inputs.petsc_ver }} --hdf5-version=${{ inputs.hdf5_ver }} --petsc-arch=${{ inputs.petsc_arch }} --modules-dir=${{ env.MODULES_DIR }}
      shell: bash

    - name: test petsc_hdf5 module
      run: |
        module load petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}/${{ inputs.petsc_arch }}
        module test petsc_hdf5/${{ inputs.petsc_ver }}_${{ inputs.hdf5_ver }}/${{ inputs.petsc_arch }}
      shell: bash --login -e -o pipefail {0}  # login to load /etc/profile.d/modules.sh
