name: setup-boost
description: build and cache boost module
inputs:
  boost_ver:
    description: boost version
    required: true
runs:
  using: composite
  steps:
    - id: set-env
      uses: ./.github/actions/set-env

    - id: cache-boost
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.set-env.outputs.modules_dir }}/opt/boost/${{ inputs.boost_ver }}
          ${{ steps.set-env.outputs.modules_dir }}/modulefiles/boost/${{ inputs.boost_ver }}
        key: |
          ${{ steps.set-env.outputs.os_ver }}-boost-${{ inputs.boost_ver }}-${{ hashFiles('scripts/install_boost.sh') }}
        restore-keys: |
          ${{ steps.set-env.outputs.os_ver }}-boost-${{ inputs.boost_ver }}-

    - name: install boost module
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        ./install_boost.sh \
          --version=${{ inputs.boost_ver }} \
          --modules-dir=${{ steps.set-env.outputs.modules_dir }}
      working-directory: ${{ github.workspace }}/scripts/custom
      shell: bash

    - name: test boost module
      run: |
        module use ${{ steps.set-env.outputs.modules_dir }}/modulefiles
        module load boost/${{ inputs.boost_ver }}
        module test boost/${{ inputs.boost_ver }}
      shell: bash --login -e -o pipefail {0} # login to source /etc/profile.d/modules.sh
