name: setup-boost
description: build and cache boost module
inputs:
  boost_ver:
    description: boost version
    required: true
runs:
  using: composite
  steps:
    - id: cache-boost
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.MODULES_DIR }}/opt/boost/${{ inputs.boost_ver }}
          ${{ env.MODULES_DIR }}/modulefiles/boost/${{ inputs.boost_ver }}
        key: ${{ env.OS_VERSION }}-boost-${{ inputs.boost_ver }}-${{ hashFiles('scripts/install_boost.sh') }}
        restore-keys: |
          ${{ env.OS_VERSION }}-boost-${{ inputs.boost_ver }}-
    
    - name: install boost module
      if: steps.cache-boost.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: ./scripts/install_boost.sh --version=${{ inputs.boost_ver }} --modules-dir=${{ env.MODULES_DIR }}
      shell: bash
        
    - name: test boost module
      run: |
        module load boost/${{ inputs.boost_ver }}
        module test boost/${{ inputs.boost_ver }}
      shell: bash --login -e -o pipefail {0}  # login to load /etc/profile.d/modules.sh
