name: setup-xsd
description: install and cache xsd module
inputs:
  xsd_ver:
    description: xsd version
    required: true
runs:
  using: composite
  steps:
    - id: set-env
      uses: ./.github/actions/set-env

    - name: test-env
      run: |
        echo ${{ steps.set-env.outputs.os_ver }}
        echo ${{ steps.set-env.outputs.modules_dir }}
        echo ${{ github.workspace }}
        ls /etc/profile.d/
        whoami
        echo $HOME
        ls /home
        ls /
      shell: bash

    - id: cache-xsd
      uses: actions/cache@v4
      with:
        path: |
          modules/opt/xsd/${{ inputs.xsd_ver }}
          modules/modulefiles/xsd/${{ inputs.xsd_ver }}
        key: |
          ${{ steps.set-env.outputs.os_ver }}-xsd-${{ inputs.xsd_ver }}-${{ hashFiles('scripts/install_xsd.sh') }}
        restore-keys: |
          ${{ steps.set-env.outputs.os_ver }}-xsd-${{ inputs.xsd_ver }}-

    - name: install xsd module
      if: steps.cache-xsd.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: |
        ./scripts/install_xsd.sh \
          --version=${{ inputs.xsd_ver }} \
          --modules-dir=${{ steps.set-env.outputs.modules_dir }}
      shell: bash

    - name: test xsd module
      run: |
        source /etc/profile.d/modules.sh
        module use ${{ steps.set-env.outputs.modules_dir }}
        module load xsd/${{ inputs.xsd_ver }}
        module test xsd/${{ inputs.xsd_ver }}
      shell: bash
