name: setup-xsd
description: install and cache xsd module
inputs:
  xsd_ver:
    description: xsd version
    required: true
runs:
  using: composite
  steps:
    - id: cache-xsd
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.MODULES_DIR }}/opt/xsd/${{ inputs.xsd_ver }}
          ${{ env.MODULES_DIR }}/modulefiles/xsd/${{ inputs.xsd_ver }}
        key: ${{ env.OS_VERSION }}-xsd-${{ inputs.xsd_ver }}-${{ hashFiles('scripts/install_xsd.sh') }}
        restore-keys: |
          ${{ env.OS_VERSION }}-xsd-${{ inputs.xsd_ver }}-
    
    - name: install xsd module
      if: steps.cache-xsd.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: ./scripts/install_xsd.sh --version=${{ inputs.xsd_ver }} --modules-dir=${{ env.MODULES_DIR }}
      shell: bash
        
    - name: test xsd module
      run: |
        module load xsd/${{ inputs.xsd_ver }}
        module test xsd/${{ inputs.xsd_ver }}
      shell: bash --login -e -o pipefail {0}  # login to load /etc/profile.d/modules.sh
