name: setup-xsd
description: install and cache xsd module
inputs:
  xsd_ver:
    description: xsd version
    required: true
runs:
  using: composite
  steps:
    - id: set-env
      uses: ./.github/actions/set-env

    - id: cache-xsd
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.set-env.outputs.modules_dir }}/opt/xsd/${{ inputs.xsd_ver }}
          ${{ steps.set-env.outputs.modules_dir }}/modulefiles/xsd/${{ inputs.xsd_ver }}
        key: |
          ${{ steps.set-env.outputs.os_ver }}-xsd-${{ inputs.xsd_ver }}-${{ hashFiles('scripts/install_xsd.sh') }}
        restore-keys: |
          ${{ steps.set-env.outputs.os_ver }}-xsd-${{ inputs.xsd_ver }}-

    - name: install xsd module
      if: steps.cache-xsd.outputs.cache-hit != 'true'
      run: |
        ./install_xsd.sh \
          --version=${{ inputs.xsd_ver }} \
          --modules-dir=${{ steps.set-env.outputs.modules_dir }}
      working-directory: ${{ github.workspace }}/scripts
      shell: bash

    - name: test xsd module
      run: |
        ls -R ${{ steps.set-env.outputs.modules_dir }}
        module use ${{ steps.set-env.outputs.modules_dir }}
        module avail
        module load xsd/${{ inputs.xsd_ver }}
        module test xsd/${{ inputs.xsd_ver }}
      shell: bash --login -e -o pipefail {0}  # login to source /etc/profile.d/modules.sh
