name: setup-xercesc
description: Build and cache xercesc module
inputs:
  os:
    description: OS
    required: true
  modules_dir:
    description: Modules base directory
    required: true
  xercesc_ver:
    description: Xerces-C version
    required: true
runs:
  using: composite
  steps:
    - name: Cache xercesc module
      id: cache-xercesc
      uses: actions/cache@v3
      with:
        path: |
          ${{ inputs.modules_dir }}/opt/xercesc/${{ inputs.xercesc_ver }}
          ${{ inputs.modules_dir }}/modulefiles/xercesc/${{ inputs.xercesc_ver }}
        key: ${{ inputs.os }}-xercesc-${{ inputs.xercesc_ver }}-${{ hashFiles('scripts/install_xercesc.sh') }}
    
    - name: Build and install xercesc module
      if: steps.cache-xercesc.outputs.cache-hit != 'true'
      run: ./scripts/install_xercesc.sh --version=${{ inputs.xercesc_ver }} --modules-dir=${{ inputs.modules_dir }}
      shell: bash
        
    - name: Check xercesc module
      run: |
        module load xercesc/${{ inputs.xercesc_ver }}
        module test xercesc/${{ inputs.xercesc_ver }}
      shell: bash --login -e -o pipefail {0}  # login to load `module` from /etc/profile.d
