name: setup-xercesc
description: build and cache xercesc module
inputs:
  xercesc_ver:
    description: xercesc version
    required: true
runs:
  using: composite
  steps:
    - id: cache-xercesc
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.MODULES_DIR }}/opt/xercesc/${{ inputs.xercesc_ver }}
          ${{ env.MODULES_DIR }}/modulefiles/xercesc/${{ inputs.xercesc_ver }}
        key: ${{ env.OS_VERSION }}-xercesc-${{ inputs.xercesc_ver }}-${{ hashFiles('scripts/install_xercesc.sh') }}
        restore-keys: |
          ${{ env.OS_VERSION }}-xercesc-${{ inputs.xercesc_ver }}-
    
    - name: build and install xercesc module
      if: steps.cache-xercesc.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: ./scripts/install_xercesc.sh --version=${{ inputs.xercesc_ver }} --modules-dir=${{ env.MODULES_DIR }}
      shell: bash
        
    - name: test xercesc module
      run: |
        module load xercesc/${{ inputs.xercesc_ver }}
        module test xercesc/${{ inputs.xercesc_ver }}
      shell: bash --login -e -o pipefail {0}  # login to load /etc/profile.d/modules.sh
