name: setup-xercesc
description: build and cache xercesc module
inputs:
  xercesc_ver:
    description: xercesc version
    required: true
runs:
  using: composite
  steps:
    - id: set-env
      uses: ./.github/actions/set-env

    - id: cache-xercesc
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.set-env.outputs.modules_dir }}/opt/xercesc/${{ inputs.xercesc_ver }}
          ${{ steps.set-env.outputs.modules_dir }}/modulefiles/xercesc/${{ inputs.xercesc_ver }}
        key: |
          ${{ steps.set-env.outputs.os_ver }}-xercesc-${{ inputs.xercesc_ver }}-${{ hashFiles('scripts/install_xercesc.sh') }}
        restore-keys: |
          ${{ steps.set-env.outputs.os_ver }}-xercesc-${{ inputs.xercesc_ver }}-
    
    - name: build and install xercesc module
      if: steps.cache-xercesc.outputs.cache-hit != 'true'
      run: |
        ./install_xercesc.sh \
          --version=${{ inputs.xercesc_ver }} \
          --modules-dir=${{ steps.set-env.outputs.modules_dir }}
      working-directory: ${{ github.workspace }}/scripts/custom
      shell: bash
        
    - name: test xercesc module
      run: |
        module use ${{ steps.set-env.outputs.modules_dir }}/modulefiles
        module load xercesc/${{ inputs.xercesc_ver }}
        module test xercesc/${{ inputs.xercesc_ver }}
      shell: bash --login -e -o pipefail {0}  # login to source /etc/profile.d/modules.sh
