name: setup-vtk
description: build and cache vtk module
inputs:
  vtk_ver:
    description: vtk version
    required: true
runs:
  using: composite
  steps:
    - id: cache-vtk
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.MODULES_DIR }}/opt/vtk/${{ inputs.vtk_ver }}
          ${{ env.MODULES_DIR }}/modulefiles/vtk/${{ inputs.vtk_ver }}
        key: ${{ env.OS_VERSION }}-vtk-${{ inputs.vtk_ver }}-${{ hashFiles('scripts/install_vtk.sh') }}
        restore-keys: |
          ${{ env.OS_VERSION }}-vtk-${{ inputs.vtk_ver }}-
    
    - name: Build and install vtk module
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: ./scripts/install_vtk.sh --version=${{ inputs.vtk_ver }} --modules-dir=${{ env.MODULES_DIR }}
      shell: bash
        
    - name: test vtk module
      run: |
        module load vtk/${{ inputs.vtk_ver }}
        module test vtk/${{ inputs.vtk_ver }}
      shell: bash --login -e -o pipefail {0}  # login to load /etc/profile.d/modules.sh
