name: setup-vtk
description: build and cache vtk module
inputs:
  vtk_ver:
    description: vtk version
    required: true
runs:
  using: composite
  steps:
    - id: set-env
      uses: ./.github/actions/set-env

    - id: cache-vtk
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.set-env.outputs.modules_dir }}/opt/vtk/${{ inputs.vtk_ver }}
          ${{ steps.set-env.outputs.modules_dir }}/modulefiles/vtk/${{ inputs.vtk_ver }}
        key: |
          ${{ steps.set-env.outputs.os_ver }}-vtk-${{ inputs.vtk_ver }}-${{ hashFiles('scripts/install_vtk.sh') }}
        restore-keys: |
          ${{ steps.set-env.outputs.os_ver }}-vtk-${{ inputs.vtk_ver }}-

    - name: build and install vtk module
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      run: |
        ./install_vtk.sh \
          --version=${{ inputs.vtk_ver }} \
          --modules-dir=${{ steps.set-env.outputs.modules_dir }}
      working-directory: ${{ github.workspace }}/scripts
      shell: bash

    - name: test vtk module
      run: |
        module use ${{ steps.set-env.outputs.modules_dir }}/modulefiles
        module load vtk/${{ inputs.vtk_ver }}
        module test vtk/${{ inputs.vtk_ver }}
      shell: bash --login -e -o pipefail {0} # login to source /etc/profile.d/modules.sh
