name: boost

on:
  workflow_dispatch:

jobs:
  setup:
    name: build and cache boost versions

    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup defaults
        uses: ./.github/actions/setup-defaults

      - name: build and cache boost 1.74.0
        uses: ./.github/actions/setup-boost
        with:
          boost_ver: 1.74.0

      - name: build and cache boost 1.71.0
        uses: ./.github/actions/setup-boost
        with:
          boost_ver: 1.71.0

      - name: build and cache boost 1.69.0
        uses: ./.github/actions/setup-boost
        with:
          boost_ver: 1.69.0

      - name: build and cache boost 1.67.0
        uses: ./.github/actions/setup-boost
        with:
          boost_ver: 1.67.0

      - name: build and cache boost 1.66.0
        uses: ./.github/actions/setup-boost
        with:
          boost_ver: 1.66.0

      - name: build and cache boost 1.64.0
        uses: ./.github/actions/setup-boost
        with:
          boost_ver: 1.64.0

      - name: build and cache boost 1.62.0
        uses: ./.github/actions/setup-boost
        with:
          boost_ver: 1.62.0
