name: boost

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache Boost versions
    
    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, boost_ver: 1.74.0}
          - {os: ubuntu-22.04, boost_ver: 1.75.0}
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup defaults
        uses: ./.github/actions/setup-defaults
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}

      - name: Build and cache boost module
        uses: ./.github/actions/setup-boost
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          boost_ver: ${{ matrix.boost_ver }}
