name: boost

on:
  workflow_dispatch:
    inputs:
      boost_ver:
        description: "Boost version"
        required: true
        type: string
        default: "1.83.0"

      os:
        description: "OS"
        required: true
        type: choice
        options:
          - "ubuntu:22.04"
          - "ubuntu:24.04"
        default: "ubuntu:24.04"

jobs:
  setup:
    name: build and cache boost

    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup os
        uses: ./.github/actions/setup-defaults

      - name: build and cache
        uses: ./.github/actions/setup-boost
        with:
          boost_ver: ${{ github.event.inputs.boost_ver }}
