name: Build HDF5

on:
  workflow_dispatch:
    inputs:
      hdf5_ver:
        description: "HDF5 version"
        required: true
        type: string
        default: "1.10.10"

defaults:
  run:
    shell: bash --login -e -o pipefail {0} # login for environment modules
    working-directory: ./scripts/custom

jobs:
  setup:
    name: Build HDF5 ${{github.event.inputs.hdf5_ver }}

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env
        run: |
          echo "MODULES_DIR=$HOME/modules" >> $GITHUB_ENV
          echo "HDF5_VER=${{ github.event.inputs.hdf5_ver }}" >> $GITHUB_ENV

      - name: Setup OS
        run: |
          sudo ./setup_custom.sh

      - name: List environment modules
        run: |
          module avail

      - name: Run build script
        run: |
          ./install_hdf5.sh \
            --version=${{ env.HDF5_VER }} \
            --modules-dir=${{ env.MODULES_DIR }}

      - name: Test
        run: |
          module use ${{ env.MODULES_DIR }}/modulefiles
          module avail
          module load hdf5/${{ env.HDF5_VER }}
          module test hdf5/${{ env.HDF5_VER }}
