name: Build all

on:
  workflow_dispatch:
    inputs:
      boost_ver:
        description: "Boost version"
        required: true
        type: string
        default: "1.83.0"

      hdf5_ver:
        description: "HDF5 version"
        required: true
        type: string
        default: "1.10.10"

      petsc_ver:
        description: "PETSc version"
        required: true
        type: string
        default: "3.19.2"

      petsc_arch:
        description: "PETSc arch"
        required: true
        type: choice
        options:
          - "linux-gnu"
          - "linux-gnu-opt"
        default: "linux-gnu"

      sundials_ver:
        description: "SUNDIALS version"
        required: true
        type: string
        default: "6.4.1"

      vtk_ver:
        description: "VTK version"
        required: true
        type: string
        default: "9.1.0"

      xercesc_ver:
        description: "Xerces-C version"
        required: true
        type: string
        default: "3.2.4"

      xsd_ver:
        description: "XSD version"
        required: true
        type: string
        default: "4.0.0"

      os:
        description: "OS"
        required: true
        type: choice
        options:
          - "ubuntu-22.04"
          - "ubuntu-24.04"
        default: "ubuntu-22.04"

defaults:
  run:
    shell: bash --login -e -o pipefail {0} # login for environment modules
    working-directory: ./scripts/custom

jobs:
  setup:
    name: Build all dependencies

    runs-on: ${{ github.event.inputs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Chaste
        uses: actions/checkout@v4
        with:
          repository: Chaste/Chaste
          path: Chaste

      - name: Set env
        run: |
          source /etc/os-release
          OS_ID="$(echo ${ID}${VERSION_ID} | sed 's/\.//')"
          echo "OS_ID=${OS_ID}" >> $GITHUB_ENV
          echo "MODULES_DIR=$HOME/modules" >> $GITHUB_ENV
          echo "BOOST_VER=${{ github.event.inputs.boost_ver }}" >> $GITHUB_ENV
          echo "HDF5_VER=${{ github.event.inputs.hdf5_ver }}" >> $GITHUB_ENV
          echo "PETSC_VER=${{ github.event.inputs.petsc_ver }}" >> $GITHUB_ENV
          echo "PETSC_ARCH=${{ github.event.inputs.petsc_arch }}" >> $GITHUB_ENV
          echo "SUNDIALS_VER=${{ github.event.inputs.sundials_ver }}" >> $GITHUB_ENV
          echo "VTK_VER=${{ github.event.inputs.vtk_ver }}" >> $GITHUB_ENV
          echo "XERCESC_VER=${{ github.event.inputs.xercesc_ver }}" >> $GITHUB_ENV
          echo "XSD_VER=${{ github.event.inputs.xsd_ver }}" >> $GITHUB_ENV

      - name: Setup OS
        run: |
          sudo ./setup_${{ env.OS_ID }}.sh

      - name: List environment modules
        run: |
          module avail

      - name: Build Boost
        run: |
          module use ${{ env.MODULES_DIR }}/modulefiles

          ./install_boost.sh \
            --version=${{ env.BOOST_VER }} \
            --modules-dir=${{ env.MODULES_DIR }}

          module test boost/${{ env.BOOST_VER }}

      - name: Build XSD
        run: |
          module use ${{ env.MODULES_DIR }}/modulefiles
          module load boost/${{ env.BOOST_VER }}

          ./install_xsd.sh \
            --version=${{ env.XSD_VER }} \
            --modules-dir=${{ env.MODULES_DIR }}

          module test xsd/${{ env.XSD_VER }}

      - name: Build Xerces-C
        run: |
          module use ${{ env.MODULES_DIR }}/modulefiles
          module load boost/${{ env.BOOST_VER }}
          module load xsd/${{ env.XSD_VER }}

          ./install_xercesc.sh \
            --version=${{ env.XERCESC_VER }} \
            --modules-dir=${{ env.MODULES_DIR }}

          module test xercesc/${{ env.XERCESC_VER }}

      - name: Build PETSc + HDF5
        run: |
          module use ${{ env.MODULES_DIR }}/modulefiles
          module load boost/${{ env.BOOST_VER }}
          module load xsd/${{ env.XSD_VER }}
          module load xercesc/${{ env.XERCESC_VER }}

          ./install_petsc_hdf5.sh \
            --petsc-version=${{ env.PETSC_VER }} \
            --petsc-arch=${{ env.PETSC_ARCH }} \
            --hdf5-version=${{ env.HDF5_VER }} \
            --modules-dir=${{ env.MODULES_DIR }}

          module test petsc_hdf5/${{ env.PETSC_VER }}_${{ env.HDF5_VER }}/${{ env.PETSC_ARCH }}

      - name: Build SUNDIALS
        run: |
          module use ${{ env.MODULES_DIR }}/modulefiles
          module load boost/${{ env.BOOST_VER }}
          module load xsd/${{ env.XSD_VER }}
          module load xercesc/${{ env.XERCESC_VER }}
          module load petsc_hdf5/${{ env.PETSC_VER }}_${{ env.HDF5_VER }}/${{ env.PETSC_ARCH }}

          ./install_sundials.sh \
            --version=${{ env.SUNDIALS_VER }} \
            --modules-dir=${{ env.MODULES_DIR }}

          module test sundials/${{ env.SUNDIALS_VER }}

      - name: Build VTK
        run: |
          module use ${{ env.MODULES_DIR }}/modulefiles
          module load boost/${{ env.BOOST_VER }}
          module load xsd/${{ env.XSD_VER }}
          module load xercesc/${{ env.XERCESC_VER }}
          module load petsc_hdf5/${{ env.PETSC_VER }}_${{ env.HDF5_VER }}/${{ env.PETSC_ARCH }}
          module load sundials/${{ env.SUNDIALS_VER }}

          ./install_vtk.sh \
            --version=${{ env.VTK_VER }} \
            --modules-dir=${{ env.MODULES_DIR }}
            
          module test vtk/${{ env.VTK_VER }}

      - name: List environment modules
        run: |
          module use ${{ env.MODULES_DIR }}/modulefiles
          module avail

      - name: TestChasteBuildInfo
        run: |
          module use ${{ env.MODULES_DIR }}/modulefiles
          module load boost/${{ env.BOOST_VER }}
          module load xsd/${{ env.XSD_VER }}
          module load xercesc/${{ env.XERCESC_VER }}
          module load petsc_hdf5/${{ env.PETSC_VER }}_${{ env.HDF5_VER }}/${{ env.PETSC_ARCH }}
          module load sundials/${{ env.SUNDIALS_VER }}
          module load vtk/${{ env.VTK_VER }}

          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j $(nproc) TestChasteBuildInfo
          ctest -V -R TestChasteBuildInfo$ | tee buildinfo
        working-directory: Chaste

      - name: Verify dependency versions
        run: |
          sed -i.bak 's/"//g' buildinfo  # remove quotes from old sundials versions

          maj_min_rev='^[0-9]\+\.[0-9]\+\.[0-9]\+'
          maj_min='^[0-9]\+\.[0-9]\+'

          boost_ver="$(echo ${{ env.BOOST_VER }} | grep -o ${maj_min_rev})"
          grep "<Boost>${boost_ver}</Boost>" buildinfo

          hdf5_ver="$(echo ${{ env.HDF5_VER }} | grep -o ${maj_min_rev})"
          grep "<HDF5>${hdf5_ver}</HDF5>" buildinfo

          petsc_ver="$(echo ${{ env.PETSC_VER }} | grep -o ${maj_min_rev})"
          grep "<PETSc>${petsc_ver}</PETSc>" buildinfo

          sundials_ver="$(echo ${{ env.SUNDIALS_VER }} | grep -o ${maj_min_rev})"
          grep "<SUNDIALS>${sundials_ver}</SUNDIALS>" buildinfo

          vtk_ver="$(echo ${{ env.VTK_VER }} | grep -o ${maj_min})"
          grep "<VTK>${vtk_ver}</VTK>" buildinfo

          xercesc_ver="$(echo ${{ env.XERCESC_VER }} | grep -o ${maj_min_rev})"
          grep "<Xerces>${xercesc_ver}</Xerces>" buildinfo

          xsd_ver="$(echo ${{ env.XSD_VER }} | grep -o ${maj_min_rev})"
          grep "<XSD>${xsd_ver}</XSD>" buildinfo
        working-directory: Chaste/build
