name: Coverage

on:
  workflow_dispatch:

jobs:
  
  build-and-test:

    runs-on: ubuntu-22.04
    container:
      image: chaste/runner:latest
      env:
        RUNNER_OFF: 1
      options: --user 0 --cpus 2
      
    env:
      CC: gcc
      CXX: g++
      
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          repository: Chaste/Chaste
          
      - name: compiler version
        run: |
          ${CXX} --version
        
      - name: make build and test directories
        run: |
          mkdir -p chaste-build-dir
          mkdir -p chaste-test-dir
          echo "CHASTE_TEST_OUTPUT=$(pwd)/chaste-test-dir" >> ${GITHUB_ENV}
          
      - name: add chaste user
        run: |
          useradd -r -s /bin/bash chaste
          cd ../..
          chown -R chaste:chaste .
          
      - name: create init script
        run: |
          echo "su - chaste" > init.sh
          echo "source /etc/profile.d/modules.sh" >> init.sh
          echo "module use /home/runner/modules/modulefiles" >> init.sh
          echo "module purge" >> init.sh
          echo "module load petsc_hdf5" >> init.sh
        working-directory: chaste-build-dir

      - name: cmake configure
        run: |
          source init.sh
          cmake -DCMAKE_BUILD_TYPE=Debug -DChaste_COVERAGE_CPUS=2 ..
        working-directory: chaste-build-dir

      - name: build test suites
        run: |
          source init.sh
          cmake --build . --target Continuous Parallel --parallel 2
        working-directory: chaste-build-dir

      - name: run test suites
        run: |
          source init.sh
          ctest -j2 -L Continuous --output-on-failure
          ctest -L Parallel  --output-on-failure
        working-directory: chaste-build-dir

      - name: run coverage
        run: |
          source init.sh
          lcov --config-file ../cmake/Config/lcovrc --directory . --capture --output-file coverage.info
          lcov --config-file ../cmake/Config/lcovrc --remove coverage.info '/usr/*' '*/fortests/*' '*/test/*' '*/3rdparty/*' '*/global/src/random/*' 'Debug/*' 'Debug_*/*' '*/cxxtest/*' --output-file coverage.info
        working-directory: chaste-build-dir

#       - name: upload to codecov
#         run: |
#           curl -Os https://uploader.codecov.io/latest/linux/codecov
#           chmod +x codecov
#           ./codecov
#         working-directory: chaste-build-dir
