name: docker-portability

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: chaste/runner:jammy.portability01
            build-args: |
              BASE: jammy
              XSD: 4.0.0
              XERCESC: 3.2.0
              SUNDIALS: 2.7.0
              BOOST: 1.62.0
              VTK: 6.3.0
              PETSC: 3.7.7
              HDF5: 1.10.0-patch1

          - tag: chaste/runner:jammy.portability07
            build-args: |
              BASE: jammy
              XSD: 4.0.0
              XERCESC: 3.2.4
              SUNDIALS: 6.5.0
              BOOST: 1.81.0
              VTK: 9.2.6
              PETSC: 3.18.5
              HDF5: 1.12.2
            
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          load: true
          tags: ${{ matrix.tag }}
          build-args: ${{ matrix.build-args }}
            
      - name: Test image
        run: |
          docker run --rm --entrypoint /bin/bash ${{ matrix.tag }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          push: true
          tags: ${{ matrix.tag }}
          build-args: ${{ matrix.build-args }}
