name: docker-portability-system

on:
  workflow_dispatch:
    inputs:
      ubuntu_release:
        description: "Ubuntu release"
        required: true
        type: string
        default: "mantic"

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - tags: |
              chaste/runner:${{ github.event.inputs.ubuntu_release }}.portability-system
            build-args: BASE=${{ github.event.inputs.ubuntu_release }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.system
          pull: true
          load: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}

      - name: Test image
        run: |
          tags=( ${{ matrix.tags }} )
          for tag in "${tags[@]}"; do
            docker run --rm --entrypoint /bin/bash ${tag}
          done

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.system
          pull: true
          push: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}
