name: docker-portability-05

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - tags: |
              chaste/runner:jammy.portability-05
            build-args: |
              BASE=jammy
              XSD=4.0.0
              XERCESC=3.2.4
              SUNDIALS=6.0.0
              BOOST=1.74.0
              VTK=9.1.0
              PETSC=3.15.5
              HDF5=1.10.8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          load: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}

      - name: Test image
        run: |
          tags=( ${{ matrix.tags }} )
          for tag in "${tags[@]}"; do
            docker run --rm --entrypoint /bin/bash ${tag}
          done

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          push: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}
