name: docker-release

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - tags: |
              chaste/runner:jammy
              chaste/runner:latest
            build-args: |
              BASE=jammy
          - tags: |
              chaste/runner:focal
            build-args: |
              BASE=focal
            
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          load: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}
            
      - name: Test image
        run: |
          tags=( ${{ matrix.tags }} )
          for tag in "${tags[@]}"; do
            docker run --rm --entrypoint /bin/bash ${tag}
          done

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          push: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}
