name: docker-portability-02

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - tags: |
              chaste/runner:jammy.portability-02
            build-args: |
              BASE=jammy
              XSD=4.0.0
              XERCESC=3.2.2
              SUNDIALS=3.2.1
              BOOST=1.69.0
              VTK=7.1.1
              PETSC=3.13.6
              HDF5=1.10.5
            
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          load: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}
            
      - name: Test image
        run: |
          tags=( ${{ matrix.tags }} )
          for tag in "${tags[@]}"; do
            docker run --rm --entrypoint /bin/bash ${tag}
          done
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          push: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}
