name: Portability

on:
  workflow_dispatch:
    inputs:
      chaste_branch:
        description: "Chaste branch"
        required: true
        type: string
        default: "develop"

      image_tag:
        description: "Portability image tag"
        required: true
        type: string
        default: "jammy.portability-01"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: "chaste/runner:${{ github.event.inputs.image_tag }}"
      env:
        RUNNER_OFF: 1
      options: --user runner

    defaults:
      run:
        shell: bash --login -e -o pipefail {0} # login for environment modules
        working-directory: /home/runner/Chaste/build

    steps:
      - name: Checkout Chaste/${{ github.event.inputs.chaste_branch }}
        run: |
          git clone -b ${{ github.event.inputs.chaste_branch }} https://github.com/Chaste/Chaste
          cd Chaste && mkdir build
        working-directory: /home/runner

      - name: Create build env init script
        run: |
          cat > init_build_env.sh << 'EOF'
          module use /home/runner/modules/modulefiles
          module load boost petsc_hdf5 sundials vtk xercesc xsd
          EOF

          cat init_build_env.sh

      - name: Configure
        run: |
          source init_build_env.sh
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: TestChasteBuildInfo
        run: |
          source init_build_env.sh
          cmake --build . --target TestChasteBuildInfo --parallel $(nproc)
          ctest -V -R TestChasteBuildInfo --output-on-failure

      - name: Build Continuous test pack
        run: |
          source init_build_env.sh
          cmake --build . --target Continuous --parallel $(nproc)

      - name: Build Nightly test pack
        run: |
          source init_build_env.sh
          cmake --build . --target Nightly --parallel $(nproc)

      - name: Run Continuous test pack
        run: |
          source init_build_env.sh
          ctest -j $(nproc) -L Continuous --output-on-failure

      - name: Run Nightly test pack
        run: |
          source init_build_env.sh
          ctest -j $(nproc) -L Nightly --output-on-failure
