name: manual-tests

on:
  workflow_dispatch:
    inputs:
      chaste_branch:
        description: 'Chaste branch'
        required: true
        type: string
        default: 'develop'

      test_suites:
        description: 'Test suites'
        required: true
        type: string
        default: 'Continuous,Nightly,Parallel'

      xsd_ver:
        description: 'XSD version'
        required: true
        type: string 
        default: '4.0.0'

      xercesc_ver:
        description: 'Xerces-C version'
        required: true
        type: string 
        default: '3.2.3'

      sundials_ver:
        description: 'Sundials version'
        required: false
        type: string 
        default: '5.8.0'

      boost_ver:
        description: 'Boost version'
        required: true
        type: string 
        default: '1.73.0'

      vtk_ver:
        description: 'VTK version'
        required: false
        type: string 
        default: '6.3.0'

      petsc_ver:
        description: 'PETSc version'
        required: true
        type: string 
        default: '3.8.4'

      petsc_arch:
        description: 'PETSc arch'
        required: true
        type: string
        default: 'linux-gnu'
      
      hdf5_ver:
        description: 'HDF5 version'
        required: true
        type: string 
        default: '1.10.1'
          
jobs:
  build-and-test:
    uses: Chaste/dependency-modules/.github/workflows/version-tests.yml@main
    with:
      chaste_branch: ${{ github.event.inputs.chaste_branch }}
      test_suites: ${{ github.event.inputs.test_suites }}
      xsd_ver: ${{ github.event.inputs.xsd_ver }}
      xercesc_ver: ${{ github.event.inputs.xercesc_ver }}
      sundials_ver: ${{ github.event.inputs.sundials_ver }}
      boost_ver: ${{ github.event.inputs.boost_ver }}
      vtk_ver: ${{ github.event.inputs.vtk_ver }}
      petsc_ver: ${{ github.event.inputs.petsc_ver }}
      petsc_arch: ${{ github.event.inputs.petsc_arch }}
      hdf5_ver: ${{ github.event.inputs.hdf5_ver }}
