name: manual-tests

on:
  workflow_dispatch:
    inputs:
      chaste_branch:
        description: 'Chaste branch'
        required: true
        type: string
        default: 'develop'

      test_suites:
        description: 'Test suites'
        required: true
        type: string
        default: 'Continuous,Nightly,Weekly'

      xsd_ver:
        description: 'XSD version'
        required: true
        type: choice
        options:
          - '4.0.0'
        default: '4.0.0'

      xercesc_ver:
        description: 'Xerces-C version'
        required: true
        type: choice
        options:
          - '3.2.2'
          - '3.2.3'
          - '3.2.3'
          - '3.2.4'
        default: '3.2.3'

      sundials_ver:
        description: 'Sundials version'
        required: false
        type: choice
        options:
          - ''
          - '3.1.2'
          - '3.2.1'
          - '4.0.2'
          - '4.1.0'
          - '5.0.0'
          - '5.1.0'
          - '5.2.0'
          - '5.4.0'
          - '5.5.0'
          - '5.6.1'
          - '5.7.0'
          - '5.8.0'
          - '6.0.0'
          - '6.1.1'
          - '6.2.0'
          - '6.3.0'
          - '6.4.1'
          - '6.5.0'
        default: '5.8.0'

      boost_ver:
        description: 'Boost version'
        required: true
        type: choice
        options:
          - '1.67.0'
          - '1.68.0'
          - '1.69.0'
          - '1.70.0'
          - '1.71.0'
          - '1.72.0'
          - '1.73.0'
          - '1.74.0'
          - '1.75.0'
          - '1.76.0'
          - '1.77.0'
          - '1.78.0'
          - '1.79.0'
          - '1.80.0'
          - '1.81.0'
        default: '1.74.0'

      vtk_ver:
        description: 'VTK version'
        required: false
        type: choice
        options:
          - ''
          - '6.3.0'
          - '7.1.0'
          - '8.1.0'
          - '8.2.0'
          - '9.1.0'
          - '9.2.0'
        default: '7.1.0'

      petsc_hdf5_ver:
        description: 'PETSc + HDF5 versions'
        required: true
        type: choice
        options:
          - '3.12.4 + 1.10.5'
          - '3.13.6 + 1.10.6'
          - '3.14.6 + 1.10.7'
          - '3.15.5 + 1.10.8'
        default: '3.12.4 + 1.10.5'
        
jobs:
  versions:
    runs-on: [self-hosted]
    timeout-minutes: 60
    
    defaults:
      run:
        shell: bash

    outputs:
      petsc_ver: ${{ steps.parse.outputs.petsc_ver }}
      hdf5_ver: ${{ steps.parse.outputs.hdf5_ver }}
      
    steps:
      - id: parse
        run: |
          petsc_hdf5_ver=($(echo "${{ github.event.inputs.petsc_hdf5_ver }}" | tr '+' '\n'))
          petsc_ver=${petsc_hdf5_ver[0]}
          hdf5_ver=${petsc_hdf5_ver[1]}
          echo "petsc_ver=${petsc_ver}" >> ${GITHUB_OUTPUT}
          echo "hdf5_ver=${hdf5_ver}" >> ${GITHUB_OUTPUT}

  build-and-test:
    needs: versions
    uses: ./.github/workflows/version-tests.yml
    with:
      chaste_branch: ${{ github.event.inputs.chaste_branch }}
      test_suites: ${{ github.event.inputs.test_suites }}
      xsd_ver: ${{ github.event.inputs.xsd_ver }}
      xercesc_ver: ${{ github.event.inputs.xercesc_ver }}
      sundials_ver: ${{ github.event.inputs.sundials_ver }}
      boost_ver: ${{ github.event.inputs.boost_ver }}
      vtk_ver: ${{ github.event.inputs.vtk_ver }}
      petsc_ver: ${{ needs.versions.outputs.petsc_ver }}
      petsc_arch: linux-gnu
      hdf5_ver: ${{ needs.versions.outputs.hdf5_ver }}
