name: Build PETSc + HDF5

on:
  workflow_dispatch:
    inputs:
      petsc_ver:
        description: "PETSc version"
        required: true
        type: string
        default: "3.19.2"

      petsc_arch:
        description: "PETSc arch"
        required: true
        type: choice
        options:
          - "linux-gnu"
          - "linux-gnu-opt"
        default: "linux-gnu"

      hdf5_ver:
        description: "HDF5 version"
        required: true
        type: string
        default: "1.10.10"

      os:
        description: "OS"
        required: true
        type: choice
        options:
          - "ubuntu-22.04"
          - "ubuntu-24.04"
        default: "ubuntu-22.04"

defaults:
  run:
    shell: bash --login -e -o pipefail {0} # login for environment modules
    working-directory: ./scripts/custom

jobs:
  setup:
    name: Build PETSc ${{ github.event.inputs.petsc_ver }} + HDF5 ${{github.event.inputs.hdf5_ver }}

    runs-on: ${{ github.event.inputs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env
        run: |
          source /etc/os-release
          OS_ID="$(echo ${ID}${VERSION_ID} | sed 's/\.//')"
          echo "OS_ID=${OS_ID}" >> $GITHUB_ENV
          echo "MODULES_DIR=$HOME/modules" >> $GITHUB_ENV
          echo "PETSC_VER=${{ github.event.inputs.petsc_ver }}" >> $GITHUB_ENV
          echo "PETSC_ARCH=${{ github.event.inputs.petsc_arch }}" >> $GITHUB_ENV
          echo "HDF5_VER=${{ github.event.inputs.hdf5_ver }}" >> $GITHUB_ENV

      - name: Setup OS
        run: |
          sudo ./setup_${{ env.OS_ID }}.sh

      - name: List environment modules
        run: |
          module avail

      - name: Run build script
        run: |
          ./install_petsc_hdf5.sh \
            --petsc-version=${{ env.PETSC_VER }} \
            --petsc-arch=${{ env.PETSC_ARCH }} \
            --hdf5-version=${{ env.HDF5_VER }} \
            --modules-dir=${{ env.MODULES_DIR }}

      - name: Test
        run: |
          module use ${MODULES_DIR}/modulefiles
          module avail
          module load petsc_hdf5/${{ env.PETSC_VER }}_${{ env.HDF5_VER }}/${{ env.PETSC_ARCH }}
          module test petsc_hdf5/${{ env.PETSC_VER }}_${{ env.HDF5_VER }}/${{ env.PETSC_ARCH }}
