name: petsc_hdf5

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache PETSC-HDF5 versions
    
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup defaults
        uses: ./.github/actions/setup-defaults
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}

      - name: Build and cache petsc 3.12.4 hdf5 1.10.4 linux-gnu
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.12.4
          hdf5_ver: 1.10.4
          petsc_arch: linux-gnu

      - name: Build and cache petsc 3.12.4 hdf5 1.10.4 linux-gnu-opt
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.12.4
          hdf5_ver: 1.10.4
          petsc_arch: linux-gnu-opt

      - name: Build and cache petsc 3.11.3 hdf5 1.10.5 linux-gnu
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.11.3
          hdf5_ver: 1.10.5
          petsc_arch: linux-gnu

      - name: Build and cache petsc 3.11.3 hdf5 1.10.5 linux-gnu-opt
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.11.3
          hdf5_ver: 1.10.5
          petsc_arch: linux-gnu-opt

      - name: Build and cache petsc 3.10.5 hdf5 1.10.4 linux-gnu
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.10.5
          hdf5_ver: 1.10.4
          petsc_arch: linux-gnu

      - name: Build and cache petsc 3.10.5 hdf5 1.10.4 linux-gnu-opt
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.10.5
          hdf5_ver: 1.10.4
          petsc_arch: linux-gnu-opt

      - name: Build and cache petsc 3.9.4 hdf5 1.10.3 linux-gnu
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.9.4
          hdf5_ver: 1.10.3
          petsc_arch: linux-gnu

      - name: Build and cache petsc 3.9.4 hdf5 1.10.3 linux-gnu-opt
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.9.4
          hdf5_ver: 1.10.3
          petsc_arch: linux-gnu-opt

      - name: Build and cache petsc 3.8.4 hdf5 1.8.21 linux-gnu
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.8.4
          hdf5_ver: 1.8.21
          petsc_arch: linux-gnu

      - name: Build and cache petsc 3.8.4 hdf5 1.8.21 linux-gnu-opt
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.8.4
          hdf5_ver: 1.8.21
          petsc_arch: linux-gnu-opt

      - name: Build and cache petsc 3.7.7 hdf5 1.10.0 linux-gnu
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.7.7
          hdf5_ver: 1.10.0
          petsc_arch: linux-gnu

      - name: Build and cache petsc 3.7.7 hdf5 1.10.0 linux-gnu-opt
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: 3.7.7
          hdf5_ver: 1.10.0
          petsc_arch: linux-gnu-opt
