name: petsc_hdf5

on:
  workflow_dispatch:
    inputs:
      petsc_ver:
        description: "PETSc version"
        required: true
        type: string
        default: "3.19.2"

      petsc_arch:
        description: "PETSc arch"
        required: true
        type: choice
        options:
          - "linux-gnu"
          - "linux-gnu-opt"
        default: "linux-gnu"

      hdf5_ver:
        description: "HDF5 version"
        required: true
        type: string
        default: "1.10.10"

      os:
        description: "OS"
        required: true
        type: choice
        options:
          - "ubuntu:22.04"
          - "ubuntu:24.04"
        default: "ubuntu:24.04"

jobs:
  setup:
    name: build and cache petsc_hdf5

    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup os
        uses: ./.github/actions/setup-defaults

      - name: build and cache
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          petsc_ver: ${{ github.event.inputs.petsc_ver }}
          petsc_arch: ${{ github.event.inputs.petsc_arch }}
          hdf5_ver: ${{ github.event.inputs.hdf5_ver }}
