name: petsc_hdf5

on:
  workflow_dispatch:

jobs:
  setup:
    name: build and cache petsc_hdf5 versions
    
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
      
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup defaults
        uses: ./.github/actions/setup-defaults

      - name: build and cache petsc 3.15.5 / hdf5 1.10.8 / linux-gnu
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          petsc_ver: 3.15.5
          hdf5_ver: 1.10.8
          petsc_arch: linux-gnu
