name: portability-tests

on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:
    inputs:
      weekday:
        description: 'Weekday: Sun=0, Mon=1 ... Sat=6'
        required: true
        type: choice 
        options: 
          - '0'
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'
        default: '1'
          
jobs:
  versions:
    runs-on: [self-hosted]
    timeout-minutes: 60
    
    defaults:
      run:
        shell: bash

    outputs:
      xsd_ver: ${{ steps.weekdays.outputs.xsd_ver }}
      xercesc_ver: ${{ steps.weekdays.outputs.xercesc_ver }}
      sundials_ver: ${{ steps.weekdays.outputs.sundials_ver }}
      boost_ver: ${{ steps.weekdays.outputs.boost_ver }}
      vtk_ver: ${{ steps.weekdays.outputs.vtk_ver }}
      petsc_ver: ${{ steps.weekdays.outputs.petsc_ver }}
      petsc_arch: ${{ steps.weekdays.outputs.petsc_arch }}
      hdf5_ver: ${{ steps.weekdays.outputs.hdf5_ver }}
        
    steps:
      - id: weekdays
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            weekday=${{ github.event.inputs.weekday }}
          else
            weekday=$(date +'%w')
          fi
          
          case ${weekday} in
            1)
              # Mon: Oldest on Ubuntu 18.04 LTS
              echo "Monday"
              xsd_ver=4.0.0
              xercesc_ver=3.2.0
              sundials_ver=2.7.0
              boost_ver=1.62.0
              vtk_ver=6.3.0
              petsc_ver=3.7.7
              petsc_arch=linux-gnu
              hdf5_ver=1.10.0-patch1
              ;;
            2)
              # Tue
              echo "Tuesday"
              xsd_ver=4.0.0
              xercesc_ver=3.2.1
              sundials_ver=3.1.2
              boost_ver=1.66.0
              vtk_ver=7.1.0
              petsc_ver=3.8.4
              petsc_arch=linux-gnu
              hdf5_ver=1.10.1
              ;;
            3)
              # Wed: Minimal config - no Sundials or VTK
              echo "Wednesday"
              xsd_ver=4.0.0
              xercesc_ver=3.2.2
              sundials_ver=
              boost_ver=1.67.0
              vtk_ver=
              petsc_ver=3.9.4
              petsc_arch=linux-gnu
              hdf5_ver=1.10.3
              ;;
            4)
              # Thu
              echo "Thursday"
              xsd_ver=4.0.0
              xercesc_ver=3.2.1
              sundials_ver=4.1.0
              boost_ver=1.71.0
              vtk_ver=8.1.0
              petsc_ver=3.11.3
              petsc_arch=linux-gnu
              hdf5_ver=1.10.4
              ;;
            5)
              # Fri
              echo "Friday"
              xsd_ver=4.0.0
              xercesc_ver=3.2.2
              sundials_ver=5.1.0
              boost_ver=1.73.0
              vtk_ver=8.2.0
              petsc_ver=3.12.4
              petsc_arch=linux-gnu
              hdf5_ver=1.10.5
              ;;
            6)
              # Sat: Newest on Ubuntu 22.04 LTS
              echo "Saturday"
              xsd_ver=4.0.0
              xercesc_ver=3.2.3
              sundials_ver=5.8.0
              boost_ver=1.74.0
              vtk_ver=9.1.0
              petsc_ver=3.15.5
              petsc_arch=linux-gnu
              hdf5_ver=1.10.7
              ;;
            0)
              # Sun: Bleeding Edge
              echo "Sunday"
              xsd_ver=4.0.0
              xercesc_ver=3.2.3
              sundials_ver=6.3.0
              boost_ver=1.80.0
              vtk_ver=9.1.0
              petsc_ver=3.17.4
              petsc_arch=linux-gnu
              hdf5_ver=1.12.2
              ;;
            *)
              echo "Unknown weekday: ${weekday}"
              exit 1
              ;;
          esac
          
          echo "xsd_ver=${xsd_ver}" >> ${GITHUB_OUTPUT}
          echo "xercesc_ver=${xercesc_ver}" >> ${GITHUB_OUTPUT}
          echo "sundials_ver=${sundials_ver}" >> ${GITHUB_OUTPUT}
          echo "boost_ver=${boost_ver}" >> ${GITHUB_OUTPUT}
          echo "vtk_ver=${vtk_ver}" >> ${GITHUB_OUTPUT}
          echo "petsc_ver=${petsc_ver}" >> ${GITHUB_OUTPUT}
          echo "petsc_arch=${petsc_arch}" >> ${GITHUB_OUTPUT}
          echo "hdf5_ver=${hdf5_ver}" >> ${GITHUB_OUTPUT}

  build-and-test:
    needs: versions
    uses: Chaste/dependency-modules/.github/workflows/version-tests.yml@main
    with:
      chaste_branch: develop
      test_suites: 'Continuous,Nightly,Parallel'
      xsd_ver: ${{ needs.versions.outputs.xsd_ver }}
      xercesc_ver: ${{ needs.versions.outputs.xercesc_ver }}
      sundials_ver: ${{ needs.versions.outputs.sundials_ver }}
      boost_ver: ${{ needs.versions.outputs.boost_ver }}
      vtk_ver: ${{ needs.versions.outputs.vtk_ver }}
      petsc_ver: ${{ needs.versions.outputs.petsc_ver }}
      petsc_arch: ${{ needs.versions.outputs.petsc_arch }}
      hdf5_ver: ${{ needs.versions.outputs.hdf5_ver }}
