name: sundials

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache Sundials versions
    
    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, sundials_ver: 5.8.0}
          - {os: ubuntu-22.04, sundials_ver: 5.8.0}
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash --login -e -o pipefail {0}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Setup
        run: |
          git clone --depth 1 https://github.com/Chaste/dependency-modules.git
          if [ ${{ matrix.os }} = 'ubuntu-20.04' ]; then
            sudo ./dependency-modules/scripts/setup_ubuntu2004.sh
          elif [ ${{ matrix.os }} = 'ubuntu-22.04' ]; then
            sudo ./dependency-modules/scripts/setup_ubuntu2204.sh
          else
              echo 'Unknown OS version'; exit 1
          fi
          mkdir -p ${MODULES_DIR}/modulefiles
          echo "module use ${MODULES_DIR}/modulefiles" | sudo tee -a /etc/profile.d/modules.sh
          source /etc/profile.d/modules.sh 
          module avail

      - name: Cache sundials module
        id: cache-sundials
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.MODULES_DIR }}/opt/sundials/${{ matrix.sundials_ver }}
            ${{ env.MODULES_DIR }}/modulefiles/sundials/${{ matrix.sundials_ver }}
          key: ${{ matrix.os }}-sundials-${{ matrix.sundials_ver }}-${{ hashFiles('dependency-modules/scripts/install_sundials.sh') }}
      
      - name: Build and install sundials module
        if: steps.cache-sundials.outputs.cache-hit != 'true'
        working-directory: dependency-modules/scripts
        run: ./install_sundials.sh --version=${{ matrix.sundials_ver }} --modules-dir=${MODULES_DIR}
          
      - name: Check sundials module
        run: |
          module load sundials/${{ matrix.sundials_ver }}
          module test sundials/${{ matrix.sundials_ver }}
