name: sundials

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache Sundials versions
    
    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, sundials_ver: 5.8.0}
          - {os: ubuntu-22.04, sundials_ver: 5.8.0}
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup defaults
        uses: ./.github/actions/setup-defaults
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}

      - name: Build and cache sundials module
        uses: ./.github/actions/setup-sundials
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          sundials_ver: ${{ matrix.sundials_ver }}
