name: sundials

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache Sundials versions
    
    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, sundials_ver: 5.8.0}
          - {os: ubuntu-22.04, sundials_ver: 5.8.0}
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash --login -e -o pipefail {0}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup defaults
        uses: ./.github/actions/setup-defaults
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}

      - name: Cache sundials module
        id: cache-sundials
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.MODULES_DIR }}/opt/sundials/${{ matrix.sundials_ver }}
            ${{ env.MODULES_DIR }}/modulefiles/sundials/${{ matrix.sundials_ver }}
          key: ${{ matrix.os }}-sundials-${{ matrix.sundials_ver }}-${{ hashFiles('scripts/install_sundials.sh') }}
      
      - name: Build and install sundials module
        if: steps.cache-sundials.outputs.cache-hit != 'true'
        run: ./scripts/install_sundials.sh --version=${{ matrix.sundials_ver }} --modules-dir=${MODULES_DIR}
          
      - name: Check sundials module
        run: |
          module load sundials/${{ matrix.sundials_ver }}
          module test sundials/${{ matrix.sundials_ver }}
