name: Ubuntu 20.04 Chaste Dependency Modules test suite

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Setup for Ubuntu 20.04
    runs-on: ubuntu-20.04
    
    defaults:
      run:
        shell: bash --login -e -o pipefail {0}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout Chaste/dependency-modules repository
        uses: actions/checkout@v3
        with:
          repository: Chaste/dependency-modules
          path: dependency-modules
          
      - name: Install required packages
        working-directory: dependency-modules/scripts
        run: sudo ./setup_ubuntu2004.sh

      - name: Setup modules directory
        run: |
          mkdir -p ${MODULES_DIR}/modulefiles
          echo "module use ${MODULES_DIR}/modulefiles" | sudo tee -a /etc/profile.d/modules.sh
          source /etc/profile.d/modules.sh 
          module avail
          
#       - name: Build and install xsd/4.0.0 module
#         working-directory: dependency-modules/scripts
#         run: |
#           ./install_xsd.sh --version=4.0.0 --modules-dir=${MODULES_DIR}
#           module load xsd/4.0.0
#           test ${XSD_ROOT} = ${MODULES_DIR}/opt/xsd/4.0.0 || exit 1
#           test -d ${XSD_ROOT}/bin || exit 2
#           test -d ${XSD_ROOT}/libxsd || exit 3
          
#       - name: Build and install xercesc/3.2.1 module
#         working-directory: dependency-modules/scripts
#         run: |
#           ./install_xercesc.sh --version=3.2.1 --modules-dir=${MODULES_DIR}
#           module load xercesc/3.2.1
#           test ${XERCESCROOT} = ${MODULES_DIR}/opt/xercesc/3.2.1 || exit 1
#           test -d ${XERCESCROOT}/bin || exit 2
#           test -d ${XERCESCROOT}/include || exit 3
#           test -d ${XERCESCROOT}/lib || exit 4
        
#       - name: Build and install sundials/2.7.0 module
#         working-directory: dependency-modules/scripts
#         run: |
#           ./install_sundials.sh --version=2.7.0 --modules-dir=${MODULES_DIR}
#           module load sundials/2.7.0
#           test ${SUNDIALS_ROOT} = ${MODULES_DIR}/opt/sundials/2.7.0 || exit 1
#           test -d ${SUNDIALS_ROOT}/include || exit 2
#           test -d ${SUNDIALS_ROOT}/lib || exit 3
          
#       - name: Build and install vtk/8.1.1 module
#         working-directory: dependency-modules/scripts
#         run: |
#           ./install_vtk.sh --version=8.1.1 --modules-dir=${MODULES_DIR}
#           module load vtk/8.1.1
#           test ${VTK_ROOT} = ${MODULES_DIR}/opt/vtk/8.1.1 || exit 1
#           test -d ${VTK_ROOT}/bin || exit 2
#           test -d ${VTK_ROOT}/include || exit 3
#           test -d ${VTK_ROOT}/lib || exit 4
          
      - name: Build and install boost/1.67.0 module
        working-directory: dependency-modules/scripts
        run: |
          ./install_boost.sh --version=1.67.0 --modules-dir=${MODULES_DIR}
          module load boost/1.67.0
          test ${BOOST_ROOT} = ${MODULES_DIR}/opt/boost/1.67.0 || exit 1
          test -d ${BOOST_ROOT}/include || exit 2
          test -d ${BOOST_ROOT}/lib || exit 3
        
#       - name: Build and install petsc_hdf5/3.9.4_1.10.3/linux-gnu module
#         working-directory: dependency-modules/scripts
#         run: |
#           ./install_petsc_hdf5.sh --petsc-version=3.9.4 --hdf5-version=1.10.3 --petsc-arch=linux-gnu --modules-dir=${MODULES_DIR}
#           module load petsc_hdf5/3.9.4_1.10.3/linux-gnu
#           test ${PETSC_DIR} = ${MODULES_DIR}/opt/petsc_hdf5/3.9.4_1.10.3 || exit 1
#           test ${PETSC_ARCH} = linux-gnu || exit 2
#           test -d ${PETSC_DIR}/${PETSC_ARCH}/bin || exit 3
#           test -d ${PETSC_DIR}/${PETSC_ARCH}/include || exit 4
#           test -d ${PETSC_DIR}/${PETSC_ARCH}/lib || exit 5
#           test -f ${PETSC_DIR}/${PETSC_ARCH}/lib/libhdf5.so || exit 6
#           test -f ${PETSC_DIR}/${PETSC_ARCH}/lib/libmpi.so || exit 7
#           test -f ${PETSC_DIR}/${PETSC_ARCH}/lib/libparmetis.so || exit 8
#           test -f ${PETSC_DIR}/${PETSC_ARCH}/lib/libpetsc.so || exit 9
#           test $(which h5pcc) = ${PETSC_DIR}/${PETSC_ARCH}/bin/h5pcc || exit 10
#           test $(which mpicc) = ${PETSC_DIR}/${PETSC_ARCH}/bin/mpicc || exit 11
