name: ubuntu-tests

on:
  workflow_dispatch:

jobs:
  setup:
    name: test modules on ubuntu

    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            xsd_ver: 4.0.0
            xercesc_ver: 3.2.3
            sundials_ver: 6.0.0
            boost_ver: 1.74.0
            vtk_ver: 9.1.0
            petsc_ver: 3.12.4
            hdf5_ver: 1.10.4
            petsc_arch: linux-gnu

          - os: ubuntu-20.04
            xsd_ver: 4.0.0
            xercesc_ver: 3.2.0
            sundials_ver: 4.1.0
            boost_ver: 1.62.0
            vtk_ver: 6.3.0
            petsc_ver: 3.7.7
            hdf5_ver: 1.10.0-patch1
            petsc_arch: linux-gnu

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup defaults
        uses: ./.github/actions/setup-defaults

      - name: install and cache xsd module
        uses: ./.github/actions/setup-xsd
        with:
          xsd_ver: ${{ matrix.xsd_ver }}

      - name: build and cache xercesc module
        uses: ./.github/actions/setup-xercesc
        with:
          xercesc_ver: ${{ matrix.xercesc_ver }}

      - name: build and cache sundials module
        uses: ./.github/actions/setup-sundials
        with:
          sundials_ver: ${{ matrix.sundials_ver }}

      - name: build and cache boost module
        uses: ./.github/actions/setup-boost
        with:
          boost_ver: ${{ matrix.boost_ver }}

      - name: build and cache vtk module
        uses: ./.github/actions/setup-vtk
        with:
          vtk_ver: ${{ matrix.vtk_ver }}

      - name: build and cache petsc_hdf5 module
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          petsc_ver: ${{ matrix.petsc_ver }}
          hdf5_ver: ${{ matrix.hdf5_ver }}
          petsc_arch: ${{ matrix.petsc_arch }}

      - name: checkout chaste
        uses: actions/checkout@v3
        with:
          repository: Chaste/Chaste
          path: Chaste
          submodules: recursive

      - name: make build and test directories
        run: |
          mkdir -p Chaste/build
          mkdir -p ${CHASTE_TEST_OUTPUT}

      - name: compile chaste build info
        working-directory: Chaste/build
        run: |
          module purge
          module load xsd/${{ matrix.xsd_ver }}
          module load xercesc/${{ matrix.xercesc_ver }}
          module load sundials/${{ matrix.sundials_ver }}
          module load boost/${{ matrix.boost_ver }}
          module load vtk/${{ matrix.vtk_ver }}
          module load petsc_hdf5/${{ matrix.petsc_ver }}_${{ matrix.hdf5_ver }}/${{ matrix.petsc_arch }}

          cmake \
              -DBoost_NO_BOOST_CMAKE=ON \
              -DBoost_NO_SYSTEM_PATHS=ON \
              -DBOOST_ROOT=${BOOST_ROOT} \
              -DVTK_DIR=${VTK_ROOT} \
              -DCMAKE_PREFIX_PATH=${XERCESC_ROOT} \
              -DCMAKE_BUILD_TYPE=Release \
              ..

          cmake --build . --parallel $(nproc) --target TestChasteBuildInfo

          ctest -V -R TestChasteBuildInfo --output-on-failure | tee buildinfo
        shell: bash --login -e -o pipefail {0}  # login to load /etc/profile.d/modules.sh

      - name: verify dependency versions
        working-directory: Chaste/build
        run: |
          vtk_arr=($(echo "${{ matrix.vtk_ver }}" | sed -e 's/\./ /g'))
          vtk_major=${vtk_arr[0]}
          vtk_minor=${vtk_arr[1]}

          sed -i.bak 's/"//g' buildinfo  # removes quotes from some sundials versions

          grep "<XSD>${{ matrix.xsd_ver }}</XSD>" buildinfo || exit 1
          grep "<Xerces>${{ matrix.xercesc_ver }}</Xerces>" buildinfo || exit 2
          grep "<SUNDIALS>${{ matrix.sundials_ver }}</SUNDIALS>" buildinfo || exit 3
          grep "<Boost>${{ matrix.boost_ver }}</Boost>" buildinfo || exit 4
          grep "<VTK>${vtk_major}.${vtk_minor}</VTK>" buildinfo || exit 5
          grep "<PETSc>${{ matrix.petsc_ver }}</PETSc>" buildinfo || exit 6
          grep "<HDF5>${{ matrix.hdf5_ver }}</HDF5>" buildinfo || exit 7
        shell: bash
