name: Ubuntu 20.04 Chaste Dependency Modules test suite

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Setup for Ubuntu 20.04
    runs-on: ubuntu-20.04
    
    defaults:
      run:
        shell: bash --login -i -e -o pipefail {0}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout Chaste/dependency-modules repository
        uses: actions/checkout@v3
        with:
          repository: Chaste/dependency-modules
          path: dependency-modules
          
      - name: Install required packages
        working-directory: dependency-modules/scripts
        run: sudo ./setup_ubuntu2004.sh

      - name: Test module command
        run: module avail
          
      - name: Setup modules directory
        run: |
          mkdir -p ${MODULES_DIR}/modulefiles
          sudo echo "module use ${MODULES_DIR}/modulefiles" >> /etc/profile
          
#       - name: Build and install xsd/4.0.0 module
#         working-directory: dependency-modules/scripts
#         run: ./install_xsd.sh --version=4.0.0 --modules-dir=${MODULES_DIR}
        
#       - name: Build and install xercesc/3.2.1 module
#         working-directory: dependency-modules/scripts
#         run: ./install_xercesc.sh --version=3.2.1 --modules-dir=${MODULES_DIR}
        
      - name: Build and install sundials/2.7.0 module
        working-directory: dependency-modules/scripts
        run: |
          ./install_sundials.sh --version=2.7.0 --modules-dir=${MODULES_DIR}
          module load sundials/2.7.0
          test ${SUNDIALS_ROOT} = ${MODULES_DIR}/modulefiles/sundials/2.7.0 || exit 1
          test -d ${MODULES_DIR}/opt/sundials/2.7.0/lib || exit 1
          test -d ${MODULES_DIR}/opt/sundials/2.7.0/include || exit 1
          test -d ${MODULES_DIR}/opt/sundials/2.7.0/cvode || exit 1
          test -d ${MODULES_DIR}/opt/sundials/2.7.0/nvector || exit 1
          
#       - name: Build and install vtk/8.1.1 module
#         working-directory: dependency-modules/scripts
#         run: ./install_vtk.sh --version=8.1.1 --modules-dir=${MODULES_DIR}
        
#       - name: Build and install petsc_hdf5/3.9.4_1.10.3/linux-gnu module
#         working-directory: dependency-modules/scripts
#         run: ./install_petsc_hdf5.sh --petsc-version=3.9.4 --hdf5-version=1.10.3 --petsc-arch=linux-gnu --modules-dir=${MODULES_DIR}
                
#       - name: Build and install boost/1.67.0 module
#         working-directory: dependency-modules/scripts
#         run: ./install_boost.sh --version=1.67.0 --modules-dir=${MODULES_DIR}

