name: Ubuntu 20.04 Chaste Dependency Modules test suite

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Setup for Ubuntu 20.04
    runs-on: ubuntu-20.04
    
    defaults:
      run:
        shell: bash --login -e -o pipefail {0}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      CHASTE_TEST_OUTPUT: ${{ github.workspace }}/chaste-test-dir
      
    steps:
      - name: Checkout Chaste/dependency-modules repository
        uses: actions/checkout@v3
        with:
          repository: Chaste/dependency-modules
          path: dependency-modules
        
      - name: Install required packages
        working-directory: dependency-modules/scripts
        run: sudo ./setup_ubuntu2004.sh

      - name: Setup modules directory
        run: |
          mkdir -p ${MODULES_DIR}/modulefiles
          echo "module use ${MODULES_DIR}/modulefiles" | sudo tee -a /etc/profile.d/modules.sh
          source /etc/profile.d/modules.sh 
          module avail
          
      - name: Build and install xsd/4.0.0 module
        working-directory: dependency-modules/scripts
        run: |
          ./install_xsd.sh --version=4.0.0 --modules-dir=${MODULES_DIR}
          module load xsd/4.0.0
          test ${XSD_ROOT} = ${MODULES_DIR}/opt/xsd/4.0.0 || exit 1
          test -d ${XSD_ROOT}/bin || exit 2
          test -d ${XSD_ROOT}/libxsd || exit 3
          
      - name: Build and install xercesc/3.2.1 module
        working-directory: dependency-modules/scripts
        run: |
          ./install_xercesc.sh --version=3.2.1 --modules-dir=${MODULES_DIR}
          module load xercesc/3.2.1
          test ${XERCESCROOT} = ${MODULES_DIR}/opt/xercesc/3.2.1 || exit 1
          test -d ${XERCESCROOT}/bin || exit 2
          test -d ${XERCESCROOT}/include || exit 3
          test -d ${XERCESCROOT}/lib || exit 4
        
      - name: Build and install sundials/4.1.0 module
        working-directory: dependency-modules/scripts
        run: |
          ./install_sundials.sh --version=4.1.0 --modules-dir=${MODULES_DIR}
          module load sundials/4.1.0
          test ${SUNDIALS_ROOT} = ${MODULES_DIR}/opt/sundials/4.1.0 || exit 1
          test -d ${SUNDIALS_ROOT}/include || exit 2
          test -d ${SUNDIALS_ROOT}/lib || exit 3
          
      - name: Build and install vtk/8.1.1 module
        working-directory: dependency-modules/scripts
        run: |
          ./install_vtk.sh --version=8.1.1 --modules-dir=${MODULES_DIR}
          module load vtk/8.1.1
          test ${VTK_ROOT} = ${MODULES_DIR}/opt/vtk/8.1.1 || exit 1
          test -d ${VTK_ROOT}/bin || exit 2
          test -d ${VTK_ROOT}/include || exit 3
          test -d ${VTK_ROOT}/lib || exit 4
          
      - name: Build and install boost/1.69.0 module
        working-directory: dependency-modules/scripts
        run: |
          ./install_boost.sh --version=1.69.0 --modules-dir=${MODULES_DIR}
          module load boost/1.69.0
          test ${BOOST_ROOT} = ${MODULES_DIR}/opt/boost/1.69.0 || exit 1
          test -d ${BOOST_ROOT}/include || exit 2
          test -d ${BOOST_ROOT}/lib || exit 3
        
      - name: Build and install petsc_hdf5/3.9.4_1.10.3/linux-gnu module
        working-directory: dependency-modules/scripts
        run: |
          ./install_petsc_hdf5.sh --petsc-version=3.9.4 --hdf5-version=1.10.3 --petsc-arch=linux-gnu --modules-dir=${MODULES_DIR}
          module load petsc_hdf5/3.9.4_1.10.3/linux-gnu
          test ${PETSC_DIR} = ${MODULES_DIR}/opt/petsc_hdf5/3.9.4_1.10.3 || exit 1
          test ${PETSC_ARCH} = linux-gnu || exit 2
          test -d ${PETSC_DIR}/${PETSC_ARCH}/bin || exit 3
          test -d ${PETSC_DIR}/${PETSC_ARCH}/include || exit 4
          test -d ${PETSC_DIR}/${PETSC_ARCH}/lib || exit 5
          test -f ${PETSC_DIR}/${PETSC_ARCH}/lib/libhdf5.so || exit 6
          test -f ${PETSC_DIR}/${PETSC_ARCH}/lib/libmpi.so || exit 7
          test -f ${PETSC_DIR}/${PETSC_ARCH}/lib/libparmetis.so || exit 8
          test -f ${PETSC_DIR}/${PETSC_ARCH}/lib/libpetsc.so || exit 9
          test $(which h5pcc) = ${PETSC_DIR}/${PETSC_ARCH}/bin/h5pcc || exit 10
          test $(which mpicc) = ${PETSC_DIR}/${PETSC_ARCH}/bin/mpicc || exit 11

      - name: Checkout Chaste repository
        uses: actions/checkout@v3
        with:
          repository: Chaste/Chaste
          path: Chaste
          submodules: recursive
          
      - name: Make build and test directories
        run: |
          mkdir -p Chaste/build
          mkdir -p ${CHASTE_TEST_OUTPUT}
      
      - name: Configure Chaste
        working-directory: Chaste/build
        run: |
          module purge
          module load xsd/4.0.0
          module load xercesc/3.2.1
          module load sundials/4.1.0
          module load vtk/8.1.1
          module load boost/1.69.0
          module load petsc_hdf5/3.9.4_1.10.3/linux-gnu
          cmake -DCMAKE_BUILD_TYPE=Release ..
      
      - name: Compile build info
        working-directory: Chaste/build
        run: cmake --build . --parallel $(nproc) --target TestChasteBuildInfo

      - name: Get build info
        working-directory: Chaste/build
        run: |
          ctest -j $(nproc) -V -R TestChasteBuildInfo --output-on-failure | tee buildinfo
          sed -i.bak 's/"//g' buildinfo  # removes quotes from some sundials versions

      - name: Check build info
        working-directory: Chaste/build
        run: |
          grep "<PETSc>3.9.4</PETSc>" buildinfo || exit 1
          grep "<Boost>1.69.0</Boost>" buildinfo || exit 2
          grep "<HDF5>1.10.3</HDF5>" buildinfo || exit 3
          grep "<XSD>4.0.0</XSD>" buildinfo || exit 4
          grep "<SUNDIALS>4.1.0</SUNDIALS>" buildinfo || exit 5
          grep "<VTK>8.1</VTK>" buildinfo || exit 6
          grep "<Xerces>3.2.1</Xerces>" buildinfo || exit 7
