name: ubuntu-tests

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Test on Ubuntu
    
    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, xsd_ver: 4.0.0, xercesc_ver: 3.2.3, sundials_ver: 5.8.0, boost_ver: 1.74.0, vtk_ver: 9.1.0, petsc_ver: 3.11.3, hdf5_ver: 1.10.5, petsc_arch: linux-gnu}
          - {os: ubuntu-22.04, xsd_ver: 4.0.0, xercesc_ver: 3.2.3, sundials_ver: 5.8.0, boost_ver: 1.75.0, vtk_ver: 9.1.0, petsc_ver: 3.11.3, hdf5_ver: 1.10.5, petsc_arch: linux-gnu}
      fail-fast: false
      
    runs-on: ${{ matrix.os }}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup defaults
        uses: ./.github/actions/setup-defaults
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          
      - name: Install and cache xsd module
        uses: ./.github/actions/setup-xsd
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          xsd_ver: ${{ matrix.xsd_ver }}
          
      - name: Build and cache xercesc module
        uses: ./.github/actions/setup-xercesc
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          xercesc_ver: ${{ matrix.xercesc_ver }}
          
      - name: Build and cache sundials module
        uses: ./.github/actions/setup-sundials
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          sundials_ver: ${{ matrix.sundials_ver }}
          
      - name: Build and cache boost module
        uses: ./.github/actions/setup-boost
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          boost_ver: ${{ matrix.boost_ver }}
          
      - name: Build and cache vtk module
        uses: ./.github/actions/setup-vtk
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          vtk_ver: ${{ matrix.vtk_ver }}
        
      - name: Build and cache petsc_hdf5 module
        uses: ./.github/actions/setup-petsc_hdf5
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          petsc_ver: ${{ matrix.petsc_ver }}
          hdf5_ver: ${{ matrix.hdf5_ver }}
          petsc_arch: ${{ matrix.petsc_arch }}

      - name: Checkout Chaste
        uses: actions/checkout@v3
        with:
          repository: Chaste/Chaste
          path: Chaste
          submodules: recursive
      
      - name: Compile Chaste build info
        run: |
          module purge
          module load xsd/${{ matrix.xsd_ver }}
          module load xercesc/${{ matrix.xercesc_ver }}
          module load sundials/${{ matrix.sundials_ver }}
          module load boost/${{ matrix.boost_ver }}
          module load vtk/${{ matrix.vtk_ver }}
          module load petsc_hdf5/${{ matrix.petsc_ver }}_${{ matrix.hdf5_ver }}/${{ matrix.petsc_arch }}

          mkdir -p Chaste/build && cd Chaste/build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . --parallel $(nproc) --target TestChasteBuildInfo

          ctest -V -R TestChasteBuildInfo --output-on-failure | tee buildinfo
          sed -i.bak 's/"//g' buildinfo  # removes quotes from some sundials versions
        shell: bash --login -e -o pipefail {0}  # login to load `module` from /etc/profile.d

      - name: Check Chaste build info
        working-directory: Chaste/build
        run: |
          vtk_arr=($(echo "${{ matrix.vtk_ver }}" | sed -e 's/\./ /g'))
          vtk_major=${vtk_arr[0]}
          vtk_minor=${vtk_arr[1]}

          grep "<XSD>${{ matrix.xsd_ver }}</XSD>" buildinfo || exit 1
          grep "<Xerces>${{ matrix.xercesc_ver }}</Xerces>" buildinfo || exit 2
          grep "<SUNDIALS>${{ matrix.sundials_ver }}</SUNDIALS>" buildinfo || exit 3
          grep "<Boost>${{ matrix.boost_ver }}</Boost>" buildinfo || exit 4
          grep "<VTK>${vtk_major}.${vtk_minor}</VTK>" buildinfo || exit 5
          grep "<PETSc>${{ matrix.petsc_ver }}</PETSc>" buildinfo || exit 6
          grep "<HDF5>${{ matrix.hdf5_ver }}</HDF5>" buildinfo || exit 7
        shell: bash
