name: vtk

on:
  workflow_dispatch:

jobs:
  setup:
    name: build and cache vtk versions
    
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
      
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup defaults
        uses: ./.github/actions/setup-defaults

      - name: build and cache vtk 6.3.0
        uses: ./.github/actions/setup-vtk
        with:
          vtk_ver: 6.3.0

      - name: build and cache vtk 7.1.0
        uses: ./.github/actions/setup-vtk
        with:
          vtk_ver: 7.1.0

      - name: build and cache vtk 8.1.0
        uses: ./.github/actions/setup-vtk
        with:
          vtk_ver: 8.1.0

      - name: build and cache vtk 8.2.0
        uses: ./.github/actions/setup-vtk
        with:
          vtk_ver: 8.2.0

      - name: build and cache vtk 9.0.0
        uses: ./.github/actions/setup-vtk
        with:
          vtk_ver: 9.0.0

      - name: build and cache vtk 9.1.0
        uses: ./.github/actions/setup-vtk
        with:
          vtk_ver: 9.1.0
