name: vtk

on:
  workflow_dispatch:
    inputs:
      vtk_ver:
        description: "VTK version"
        required: true
        type: string
        default: "9.1.0"

      os:
        description: "OS"
        required: true
        type: choice
        options:
          - "ubuntu:22.04"
          - "ubuntu:24.04"
        default: "ubuntu:24.04"

jobs:
  setup:
    name: build and cache vtk

    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup os
        uses: ./.github/actions/setup-defaults

      - name: build and cache
        uses: ./.github/actions/setup-vtk
        with:
          vtk_ver: ${{ github.event.inputs.vtk_ver }}
