name: vtk

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache VTK versions
    
    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, vtk_ver: 9.1.0}
          - {os: ubuntu-22.04, vtk_ver: 9.1.0}
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash --login -e -o pipefail {0}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Setup
        run: |
          git clone --depth 1 https://github.com/Chaste/dependency-modules.git
          if [ ${{ matrix.os }} = 'ubuntu-20.04' ]; then
            sudo ./dependency-modules/scripts/setup_ubuntu2004.sh
          elif [ ${{ matrix.os }} = 'ubuntu-22.04' ]; then
            sudo ./dependency-modules/scripts/setup_ubuntu2204.sh
          else
              echo 'Unknown OS version'; exit 1
          fi
          mkdir -p ${MODULES_DIR}/modulefiles
          echo "module use ${MODULES_DIR}/modulefiles" | sudo tee -a /etc/profile.d/modules.sh
          source /etc/profile.d/modules.sh 
          module avail

      - name: Cache vtk module
        id: cache-vtk
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.MODULES_DIR }}/opt/vtk/${{ matrix.vtk_ver }}
            ${{ env.MODULES_DIR }}/modulefiles/vtk/${{ matrix.vtk_ver }}
          key: ${{ matrix.os }}-vtk-${{ matrix.vtk_ver }}-${{ hashFiles('dependency-modules/scripts/install_vtk.sh') }}
      
      - name: Build and install vtk module
        if: steps.cache-vtk.outputs.cache-hit != 'true'
        working-directory: dependency-modules/scripts
        run: ./install_vtk.sh --version=${{ matrix.vtk_ver }} --modules-dir=${MODULES_DIR}
          
      - name: Check vtk module
        run: |
          module load vtk/${{ matrix.vtk_ver }}
          module test vtk/${{ matrix.vtk_ver }}
