name: Build VTK

on:
  workflow_dispatch:
    inputs:
      vtk_ver:
        description: "VTK version"
        required: true
        type: string
        default: "9.1.0"

      os:
        description: "OS"
        required: true
        type: choice
        options:
          - "ubuntu-22.04"
          - "ubuntu-24.04"
        default: "ubuntu-22.04"

defaults:
  run:
    shell: bash --login -e -o pipefail {0} # login for environment modules
    working-directory: ./scripts/custom

jobs:
  setup:
    name: Build VTK ${{ github.event.inputs.vtk_ver }}

    runs-on: ${{ github.event.inputs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env
        run: |
          source /etc/os-release
          OS_ID="$(echo ${ID}${VERSION_ID} | sed 's/\.//')"
          echo "OS_ID=${OS_ID}" >> $GITHUB_ENV
          echo "MODULES_DIR=$HOME/modules" >> $GITHUB_ENV
          echo "VTK_VER=${{ github.event.inputs.vtk_ver }}" >> $GITHUB_ENV

      - name: Setup OS
        run: |
          sudo ./setup_${{ env.OS_ID }}.sh && \
          sudo apt-get install -y libboost-dev mpi-default-bin mpi-default-dev

      - name: List environment modules
        run: |
          module avail

      - name: Run build script
        run: |
          ./install_vtk.sh \
            --version=${{ env.VTK_VER }} \
            --modules-dir=${{ env.MODULES_DIR }}

      - name: Test
        run: |
          module use ${{ env.MODULES_DIR }}/modulefiles
          module avail
          module load vtk/${{ env.VTK_VER }}
          module test vtk/${{ env.VTK_VER }}
