name: vtk

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache VTK versions
    
    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, vtk_ver: 9.1.0}
          - {os: ubuntu-22.04, vtk_ver: 9.1.0}
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup defaults
        uses: ./.github/actions/setup-defaults
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}

      - name: Build and cache vtk module
        uses: ./.github/actions/setup-vtk
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          vtk_ver: ${{ matrix.vtk_ver }}
