name: vtk

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache VTK versions
    
    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, vtk_ver: 9.1.0}
          - {os: ubuntu-22.04, vtk_ver: 9.1.0}
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash --login -e -o pipefail {0}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup defaults
        uses: ./.github/actions/setup-defaults
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}

      - name: Cache vtk module
        id: cache-vtk
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.MODULES_DIR }}/opt/vtk/${{ matrix.vtk_ver }}
            ${{ env.MODULES_DIR }}/modulefiles/vtk/${{ matrix.vtk_ver }}
          key: ${{ matrix.os }}-vtk-${{ matrix.vtk_ver }}-${{ hashFiles('scripts/install_vtk.sh') }}
      
      - name: Build and install vtk module
        if: steps.cache-vtk.outputs.cache-hit != 'true'
        run: ./scripts/install_vtk.sh --version=${{ matrix.vtk_ver }} --modules-dir=${MODULES_DIR}
          
      - name: Check vtk module
        run: |
          module load vtk/${{ matrix.vtk_ver }}
          module test vtk/${{ matrix.vtk_ver }}
