name: vtk

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache VTK versions
    
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup defaults
        uses: ./.github/actions/setup-defaults
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}

      - name: Build and cache vtk 6.3.0
        uses: ./.github/actions/setup-vtk
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          vtk_ver: 6.3.0

      - name: Build and cache vtk 7.1.0
        uses: ./.github/actions/setup-vtk
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          vtk_ver: 7.1.0

      - name: Build and cache vtk 8.1.0
        uses: ./.github/actions/setup-vtk
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          vtk_ver: 8.1.0

      - name: Build and cache vtk 8.2.0
        uses: ./.github/actions/setup-vtk
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          vtk_ver: 8.2.0

      - name: Build and cache vtk 9.0.0
        uses: ./.github/actions/setup-vtk
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          vtk_ver: 9.0.0

      - name: Build and cache vtk 9.1.0
        uses: ./.github/actions/setup-vtk
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          vtk_ver: 9.1.0
