name: xercesc

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache Xerces-C versions
    
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup defaults
        uses: ./.github/actions/setup-defaults
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}

      - name: Build and cache xercesc 3.2.2
        uses: ./.github/actions/setup-xercesc
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          xercesc_ver: 3.2.2
          
      - name: Build and cache xercesc 3.2.3
        uses: ./.github/actions/setup-xercesc
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}
          xercesc_ver: 3.2.3
