name: xercesc

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache Xerces-C versions
    
    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, xercesc_ver: 3.2.3}
          - {os: ubuntu-22.04, xercesc_ver: 3.2.3}
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash --login -e -o pipefail {0}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup defaults
        uses: ./.github/actions/setup-defaults
        with:
          os: ${{ matrix.os }}
          modules_dir: ${{ env.MODULES_DIR }}

      - name: Cache xercesc module
        id: cache-xercesc
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.MODULES_DIR }}/opt/xercesc/${{ matrix.xercesc_ver }}
            ${{ env.MODULES_DIR }}/modulefiles/xercesc/${{ matrix.xercesc_ver }}
          key: ${{ matrix.os }}-xercesc-${{ matrix.xercesc_ver }}-${{ hashFiles('scripts/install_xercesc.sh') }}
      
      - name: Build and install xercesc module
        if: steps.cache-xercesc.outputs.cache-hit != 'true'
        run: ./scripts/install_xercesc.sh --version=${{ matrix.xercesc_ver }} --modules-dir=${MODULES_DIR}
          
      - name: Check xercesc module
        run: |
          module load xercesc/${{ matrix.xercesc_ver }}
          module test xercesc/${{ matrix.xercesc_ver }}
