name: xerces

on:
  workflow_dispatch:

jobs:
  
  setup:
    name: Build and cache Xerces-C versions
    
    strategy:
      matrix:
        include:
          - {os: ubuntu-20.04, xercesc_ver: 3.2.3}
          - {os: ubuntu-22.04, xercesc_ver: 3.2.3}
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash --login -e -o pipefail {0}
        
    env:
      MODULES_DIR: ${{ github.workspace }}/modules
      
    steps:
      - name: Setup
        run: |
          git clone --depth 1 https://github.com/Chaste/dependency-modules.git
          if [ ${{ matrix.os }} = 'ubuntu-20.04' ]; then
            sudo ./dependency-modules/scripts/setup_ubuntu2004.sh
          elif [ ${{ matrix.os }} = 'ubuntu-22.04' ]; then
            sudo ./dependency-modules/scripts/setup_ubuntu2204.sh
          else
              echo 'Unknown OS version'; exit 1
          fi
          mkdir -p ${MODULES_DIR}/modulefiles
          echo "module use ${MODULES_DIR}/modulefiles" | sudo tee -a /etc/profile.d/modules.sh
          source /etc/profile.d/modules.sh 
          module avail

      - name: Cache xercesc module
        id: cache-xercesc
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.MODULES_DIR }}/opt/xercesc/${{ matrix.xercesc_ver }}
            ${{ env.MODULES_DIR }}/modulefiles/xercesc/${{ matrix.xercesc_ver }}
          key: ${{ matrix.os }}-xercesc-${{ matrix.xercesc_ver }}-${{ hashFiles('dependency-modules/scripts/install_xercesc.sh') }}
      
      - name: Build and install xercesc module
        if: steps.cache-xercesc.outputs.cache-hit != 'true'
        working-directory: dependency-modules/scripts
        run: ./install_xercesc.sh --version=${{ matrix.xercesc_ver }} --modules-dir=${MODULES_DIR}
          
      - name: Check xercesc module
        run: |
          module load xercesc/${{ matrix.xercesc_ver }}
          module test xercesc/${{ matrix.xercesc_ver }}
