name: xercesc

on:
  workflow_dispatch:
    inputs:
      xercesc_ver:
        description: 'XercesC version'
        required: true
        type: string
        default: '3.2.4'

      os:
        description: 'OS'
        required: true
        type: choice
        options:
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'
        default: 'ubuntu-22.04'

jobs:
  setup:
    name: build and cache xercesc
    
    runs-on: ${{ github.event.inputs.os }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup defaults
        uses: ./.github/actions/setup-defaults

      - name: build and cache xercesc
        uses: ./.github/actions/setup-xercesc
        with:
          xercesc_ver: ${{ github.event.inputs.xercesc_ver }}
