name: xercesc

on:
  workflow_dispatch:

jobs:
  setup:
    name: build and cache xercesc versions
    
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup defaults
        uses: ./.github/actions/setup-defaults

      - name: build and cache xercesc 3.2.0
        uses: ./.github/actions/setup-xercesc
        with:
          xercesc_ver: 3.2.0

      - name: build and cache xercesc 3.2.1
        uses: ./.github/actions/setup-xercesc
        with:
          xercesc_ver: 3.2.1

      - name: build and cache xercesc 3.2.2
        uses: ./.github/actions/setup-xercesc
        with:
          xercesc_ver: 3.2.2
          
      - name: build and cache xercesc 3.2.3
        uses: ./.github/actions/setup-xercesc
        with:
          xercesc_ver: 3.2.3
