name: Build XSD

on:
  workflow_dispatch:
    inputs:
      xsd_ver:
        description: "XSD version"
        required: true
        type: string
        default: "4.0.0"

      os:
        description: "OS"
        required: true
        type: choice
        options:
          - "ubuntu-22.04"
          - "ubuntu-24.04"
        default: "ubuntu-22.04"

defaults:
  run:
    shell: bash --login -e -o pipefail {0} # login for environment modules
    working-directory: ./scripts/custom

jobs:
  setup:
    name: Build XSD ${{ github.event.inputs.xsd_ver }}

    runs-on: ${{ github.event.inputs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env
        run: |
          source /etc/os-release
          OS_ID="$(echo ${ID}${VERSION_ID} | sed 's/\.//')"
          echo "OS_ID=${OS_ID}" >> $GITHUB_ENV
          echo "MODULES_DIR=$HOME/modules" >> $GITHUB_ENV
          echo "XSD_VER=${{ github.event.inputs.xsd_ver }}" >> $GITHUB_ENV

      - name: Setup OS
        run: |
          sudo ./setup_${{ env.OS_ID }}.sh

      - name: List environment modules
        run: |
          module avail

      - name: Run build script
        run: |
          ./install_xsd.sh \
          --version=${{ env.XSD_VER }} \
          --modules-dir=${{ env.MODULES_DIR }}

      - name: Test
        run: |
          module use ${MODULES_DIR}/modulefiles
          module avail
          module load xsd/${{ env.XSD_VER }}
          module test xsd/${{ env.XSD_VER }}
