name: xsd

on:
  workflow_dispatch:
    inputs:
      xsd_ver:
        description: "XSD version"
        required: true
        type: string
        default: "4.0.0"

      os:
        description: "OS"
        required: true
        type: choice
        options:
          - "ubuntu:22.04"
          - "ubuntu:24.04"
        default: "ubuntu:24.04"

jobs:
  setup:
    name: build and cache xsd

    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup os
        uses: ./.github/actions/setup-defaults

      - name: build and cache
        uses: ./.github/actions/setup-xsd
        with:
          xsd_ver: ${{ github.event.inputs.xsd_ver }}
